function disp = init_disp_vo(img)

pos=get(0,'ScreenSize');

titolo = ['Visual Odometry pipeline - ' ...
    'R. Pellerito, G. Manzoni, L. Piglia  -  ' ...
    'Vision Algoritms for Mobile Robotics course, fall 2021. ETH Zurich  -  ' ...
    'Prof. D. Scaramuzza'];

% create figure window and save it under fig for later referencing
fig = figure(...
    'Name',titolo,...
    'NumberTitle','off',...
    'MenuBar','none',...
    'ToolBar','none',...
    'Outerposition',[0   0   pos(3)   pos(4)-20]);

% Title of the window
titolo_fig = uicontrol('Parent',fig,...
                'Style','text',...
                'String',titolo, ...
                'Position', [10, fig.Position(4)-35, pos(3), 30],...
                'FontSize',15,...
                'FontWeight','bold');

border = 50;
upper_border = border + 10;

img_scale = 0.75;



ax_img = axes(...
    'Parent',fig,...
    'Visible','off',...
    'Units','pixels',...
    'Position',[border, fig.Position(4)-upper_border-floor(img_scale*size(img,1)),...
    floor(img_scale*size(img,2)),floor(img_scale*size(img,1))]);

ax_path_landm = axes(...
    'Parent',fig,...
    'Units','pixels',...
    'Position',[max(ax_img.Position(3), fig.Position(3)/2)+2*border, border,...
    min(fig.Position(3) - ax_img.Position(3) - 3*border, fig.Position(3)/2 - 3*border)...
    fig.Position(4) - border - upper_border]);


ax_num_keypoints = axes(...
    'Parent',fig,...
    'Units','pixels',...
    'Position',[border,border,0.5*(0.5*fig.Position(3) - 2.5*border),...
    fig.Position(4) - upper_border - border - ax_img.Position(4)]);



ax_pathfull = axes(...
    'Parent',fig,...
    'Units','pixels',...
    'Position',[ax_num_keypoints.Position(3) + 2*border,...
    border,...
    fig.Position(3) - 4*border - ax_path_landm.Position(3) - ax_num_keypoints.Position(3),...
    ax_num_keypoints.Position(4)]);



disp.fig = fig;
disp.border = border;
disp.upper_border = upper_border;
disp.ax_img = ax_img;
disp.ax_path_landm = ax_path_landm;
disp.ax_num_keypoints = ax_num_keypoints;
disp.ax_pathfull = ax_pathfull;
end